files:
  - source: Resources/Translations/Translate_EN.xml
    translation: /Resources/Translations/Translate_%two_letters_code%.%file_extension%
    translatable_elements:
      - '/ArrayOfTranslate/Translate[@translate]'
